# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: right_lower_limb
  joint_model_group_pose: stand
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - Left_Hip_Joint
    - Left_Thigh_Joint
    - Left_Calf_Joint
    - Left_Ankle_Joint
    - Right_Hip_Joint
    - Right_Thigh_Joint
    - Right_Calf_Joint
    - Right_Ankle_Joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
right_lower_limb_controller:
  type: position_controllers/JointPositionController
  joints:
    - Right_Hip_Joint
    - Right_Thigh_Joint
    - Right_Calf_Joint
    - Right_Ankle_Joint
  gains:
    Right_Hip_Joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Right_Thigh_Joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Right_Calf_Joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Right_Ankle_Joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
left_lower_limb_controller:
  type: position_controllers/JointPositionController
  joints:
    - Left_Hip_Joint
    - Left_Thigh_Joint
    - Left_Calf_Joint
    - Left_Ankle_Joint
  gains:
    Left_Hip_Joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Left_Thigh_Joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Left_Calf_Joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Left_Ankle_Joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1