# gazebo_ros_control_params.yaml
lower_limb/gazebo_ros_control/pid_gains:
  Left_Hip_Joint: {p: 100.0, i: 0.01, d: 10.0}
  Left_Thigh_Joint: {p: 100.0, i: 0.01, d: 10.0}
  Left_Calf_Joint: {p: 100.0, i: 0.01, d: 10.0}
  Left_Ankle_Joint: {p: 100.0, i: 0.01, d: 10.0}
  Right_Hip_Joint: {p: 100.0, i: 0.01, d: 10.0}
  Right_Thigh_Joint: {p: 100.0, i: 0.01, d: 10.0}
  Right_Calf_Joint: {p: 100.0, i: 0.01, d: 10.0}
  Right_Ankle_Joint: {p: 100.0, i: 0.01, d: 10.0}
lower_limb:
  # publish all joint states--------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000
  # Gazebo use controller that ros_control(joint_position_controller)
  # Position Controllers------------------
  Left_Hip_Joint_position_controller:
    type: position_controllers/JointPositionController
    joint: Left_Hip_Joint
    pid: {p: 100.0,  i: 0.0, d: 0.0, i_clamp: 1}
  Right_Hip_Joint_position_controller:
    type: position_controllers/JointPositionController
    joint: Right_Hip_Joint
    pid: {p: 100.0,  i: 0.0, d: 0.0, i_clamp: 1}

  Left_Thigh_Joint_position_controller:
    type: position_controllers/JointPositionController
    joint: Left_Thigh_Joint
    pid: {p: 100.0,  i: 0.0, d: 0.0, i_clamp: 1}
  Right_Thigh_Joint_position_controller:
    type: position_controllers/JointPositionController
    joint: Right_Thigh_Joint
    pid: {p: 100.0,  i: 0.0, d: 0.0, i_clamp: 1}   
    
  Left_Calf_Joint_position_controller:
    type: position_controllers/JointPositionController
    joint: Left_Calf_Joint
    pid: {p: 100.0,  i: 0.0, d: 0.0, i_clamp: 1}
  Right_Calf_Joint_position_controller:
    type: position_controllers/JointPositionController
    joint: Right_Calf_Joint
    pid: {p: 100.0,  i: 0.0, d: 0.0, i_clamp: 1}   

  Left_Ankle_Joint_position_controller:
    type: position_controllers/JointPositionController
    joint: Left_Ankle_Joint
    pid: {p: 100.0,  i: 0.0, d: 0.0, i_clamp: 1}
  Right_Ankle_Joint_position_controller:
    type: position_controllers/JointPositionController
    joint: Right_Ankle_Joint
    pid: {p: 100.0,  i: 0.0, d: 0.0, i_clamp: 1}   